[package]
name = "protoc-gen-tonic"
version = "0.1.0"
authors = ["Marcus Griep <marcus@griep.us>"]
description = "Protocol Buffers compiler plugin for gRPC services powered by Prost! and Tonic"
repository = "https://github.com/neoeinstein/protoc-gen-tonic"
homepage = "https://github.com/neoeinstein/protoc-gen-tonic"
documentation = "https://docs.rs/protoc-gen-tonic"
license = "Apache-2.0"
edition = "2021"
readme = "README.md"
keywords = ["protobuf", "serialization", "prost", "grpc", "tonic"]
categories = ["encoding"]
exclude = [
    "proto"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heck = "0.4.0"
once_cell = "1.10.0"
prettyplease = "0.1.9"
prost-build = { version = "0.9.0", default-features = false }
prost-types = { version = "0.9.0", default-features = false }
prost = { version = "0.9.0", default-features = false, features = ["std"] }
protoc-gen-prost = "0.1.1"
regex = { version = "1.5.5", default-features = false }
syn = { version = "1.0.89", features = ["parsing", "full"] }
tonic-build = { version = "0.6.2", features = ["compression"] }

[patch.crates-io]
prost-build = { git = "https://github.com/tokio-rs/prost", branch = "master" }
prost-types = { git = "https://github.com/tokio-rs/prost", branch = "master" }
prost = { git = "https://github.com/tokio-rs/prost", branch = "master" }
protoc-gen-prost = { git = "https://github.com/neoeinstein/protoc-gen-prost", branch = "main" }
